//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProjectOnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]

    public partial class NotificationTable
    {
        [DataMember]

        public int ID { get; set; }
        [DataMember]

        public Nullable<int> AdminID { get; set; }
        [DataMember]

        public Nullable<int> RetailerID { get; set; }
        [DataMember]

        public Nullable<int> ProductID { get; set; }
        [DataMember]

        public bool RetailerStatus { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        public virtual Product Product { get; set; }
        public virtual RetailerTable RetailerTable { get; set; }
    }
}
