//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProjectOnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]

    public partial class OrderTable
    {
        [DataMember]

        public int OrderID { get; set; }
        [DataMember]

        public System.DateTime OrderDate { get; set; }
        [DataMember]

        public Nullable<int> CartID { get; set; }
        [DataMember]

        public Nullable<int> AddressID { get; set; }
        [DataMember]

        public Nullable<int> UserID { get; set; }
    
        public virtual AddressTable AddressTable { get; set; }
        public virtual Cart Cart { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
