//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProjectOnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.NotificationTables = new HashSet<NotificationTable>();
            this.WishLists = new HashSet<WishList>();
        }

        [DataMember]

        public int ProductID { get; set; }
        [DataMember]

        public string ProductCode { get; set; }
        [DataMember]

        public string ProductName { get; set; }
        [DataMember]

        public string ProductDescription { get; set; }
        [DataMember]

        public string Brand { get; set; }
        [DataMember]

        public int Quantity { get; set; }
        [DataMember]

        public float ProductPrice { get; set; }
        [DataMember]

        public bool InStock { get; set; }
        [DataMember]

        public Nullable<int> RetailerID { get; set; }
        [DataMember]

        public Nullable<int> ImageID { get; set; }
        [DataMember]

        public Nullable<int> CategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Category Category { get; set; }
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationTable> NotificationTables { get; set; }
        public virtual RetailerTable RetailerTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
