//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProjectOnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]

    public partial class RetailerTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RetailerTable()
        {
            this.NotificationTables = new HashSet<NotificationTable>();
            this.Products = new HashSet<Product>();
        }
        [DataMember]

        public int RetailerID { get; set; }
        [DataMember]

        public string FirstName { get; set; }
        [DataMember]

        public string LastName { get; set; }
        [DataMember]

        public string Email { get; set; }
        [DataMember]

        public string MobileNumber { get; set; }
        [DataMember]

        public string Password { get; set; }
        [DataMember]

        public Nullable<System.DateTime> CreatedOn { get; set; }
        [DataMember]

        public Nullable<int> AddressID { get; set; }
    
        public virtual AddressTable AddressTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationTable> NotificationTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
