//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProjectOnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]

    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.NotificationTables = new HashSet<NotificationTable>();
            this.OrderTables = new HashSet<OrderTable>();
            this.OTPs = new HashSet<OTP>();
            this.WishLists = new HashSet<WishList>();
        }
        [DataMember]

        public int UserID { get; set; }
        [DataMember]

        public string FirstName { get; set; }
        [DataMember]

        public string LastName { get; set; }
        [DataMember]

        public string Email { get; set; }
        [DataMember]

        public string MobileNumber { get; set; }
        [DataMember]

        public string Password { get; set; }
        [DataMember]

        public Nullable<System.DateTime> CreatedOn { get; set; }
        [DataMember]

        public bool IsAdmin { get; set; }
        [DataMember]

        public Nullable<int> AddressID { get; set; }
    
        public virtual AddressTable AddressTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationTable> NotificationTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTable> OrderTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTP> OTPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
